version: 1.0.{build}
branches:
  only:
  - develop
  - master
image: Ubuntu2004
build: off

environment:
  COVERALLS_SERVICE_NAME: appveyor 
  COVERALLS_REPO_TOKEN: 25Sl8XjzDDuldcq2FscZnlq7ts1fRVhb3

init:
    - sudo apt-get update
    - sudo apt-get install -qq python3-pip
    
install: 
    - python3 -m pip install --upgrade pip
    - python3 -m pip install --upgrade numpy
    - python3 -m pip install --upgrade scipy
    - python3 -m pip install --upgrade scikit-learn
    - python3 -m pip install --upgrade matplotlib
    - python3 -m pip install --upgrade plotly
    - python3 -m pip install --upgrade kaleido
    - python3 -m pip install --upgrade pandas
    - python3 -m pip install --upgrade geopy
    - PATH=$PATH:/home/appveyor/.local/bin
    - python3 -m pip install coveralls==3.2.0
    - python3 setup.py develop --user
    - cd Regressions
    
test_script:
  coverage run automatic_regression.py test
     
on_success:
  coveralls
